// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using test_for_path_project.Models;

#nullable disable

namespace test_for_path_project.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250601211913_addtypefix")]
    partial class addtypefix
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("test_for_path_project.Models.AAU", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("التخصص")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("الحقل")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("الساعات")
                        .HasColumnType("int");

                    b.Property<int?>("السعر")
                        .HasColumnType("int");

                    b.Property<string>("الكلية")
                        .HasColumnType("nvarchar(max)");

                    b.Property<float?>("معدل_القبول")
                        .HasColumnType("real");

                    b.HasKey("Id");

                    b.ToTable("AAU_INFO");
                });

            modelBuilder.Entity("test_for_path_project.Models.MEU", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("التخصص")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("الحقل")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("الساعات")
                        .HasColumnType("int");

                    b.Property<int?>("السعر")
                        .HasColumnType("int");

                    b.Property<string>("الكلية")
                        .HasColumnType("nvarchar(max)");

                    b.Property<float?>("معدل_القبول")
                        .HasColumnType("real");

                    b.HasKey("Id");

                    b.ToTable("MEU_INFO");
                });

            modelBuilder.Entity("test_for_path_project.Models.PHU", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("التخصص")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("الحقل")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("الساعات")
                        .HasColumnType("int");

                    b.Property<int?>("السعر")
                        .HasColumnType("int");

                    b.Property<string>("الكلية")
                        .HasColumnType("nvarchar(max)");

                    b.Property<float?>("معدل_القبول")
                        .HasColumnType("real");

                    b.HasKey("Id");

                    b.ToTable("PHU_INFO");
                });

            modelBuilder.Entity("test_for_path_project.Models.University", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<float>("GPA")
                        .HasColumnType("real");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Unis");
                });

            modelBuilder.Entity("test_for_path_project.Models.test", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<string>("description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id");

                    b.ToTable("TS");
                });
#pragma warning restore 612, 618
        }
    }
}
